spring:
  application:
    name: Greet-MS
  boot:
     admin:
        client:
             url: http://localhost:1111/ 
      
server:
  port: 9091
  
management:
   endpoints:
    web:
      exposure:
        include: '*'